server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chaintract?characterEncoding=utf8
    username: chaintract
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#       show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /home/ubuntu/imageUpload/
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

